//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathewProject.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
    
    public partial class Cathedral
    {
        public Cathedral()
        {
            this.Parishes = new HashSet<Parish>();
            this.Priests = new HashSet<Priest>();
        }
    
        public int CathedralID { get; set; }
        public string CathedralName { get; set; }
        public Nullable<System.DateTime> Founded { get; set; }
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string NationalAnthem { get; set; }
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string DiocesanAnthem { get; set; }
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string PapalAnthem { get; set; }
        public string About { get; set; }
    
        public virtual ICollection<Parish> Parishes { get; set; }
        public virtual ICollection<Priest> Priests { get; set; }
    }
}
