//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathewProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parish
    {
        public int ParishID { get; set; }
        public string ParishName { get; set; }
        public Nullable<System.DateTime> Founded { get; set; }
        public string Anthem { get; set; }
        public string Location { get; set; }
        public Nullable<int> CathedralID { get; set; }
        public Nullable<int> PriestID { get; set; }
    
        public virtual Cathedral Cathedral { get; set; }
        public virtual Priest Priest { get; set; }
    }
}
